"""initial_simplified

Revision ID: 2603533e5a19
Revises: 
Create Date: 2026-05-18 22:41:52.710065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2603533e5a19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('arctracker_email', sa.String(length=255), nullable=False),
    sa.Column('arctracker_password', sa.Text(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arctracker_email')
    )
    op.create_table('character_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('embark_project_id', sa.String(length=100), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('phases', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tracker_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_projects_account_id'), 'character_projects', ['account_id'], unique=False)
    op.create_table('character_quests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('quest_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tracker_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_quests_account_id'), 'character_quests', ['account_id'], unique=False)
    op.create_table('hideout_modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tracker_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hideout_modules_account_id'), 'hideout_modules', ['account_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['tracker_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_account_id'), 'inventory_items', ['account_id'], unique=False)
    op.create_table('learned_blueprints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('blueprint_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tracker_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learned_blueprints_account_id'), 'learned_blueprints', ['account_id'], unique=False)
    op.create_table('inventory_item_mods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inventory_item_id', sa.String(length=36), nullable=False),
    sa.Column('slot_type', sa.String(length=50), nullable=False),
    sa.Column('mod_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_item_mods_inventory_item_id'), 'inventory_item_mods', ['inventory_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_item_mods_inventory_item_id'), table_name='inventory_item_mods')
    op.drop_table('inventory_item_mods')
    op.drop_index(op.f('ix_learned_blueprints_account_id'), table_name='learned_blueprints')
    op.drop_table('learned_blueprints')
    op.drop_index(op.f('ix_inventory_items_account_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_hideout_modules_account_id'), table_name='hideout_modules')
    op.drop_table('hideout_modules')
    op.drop_index(op.f('ix_character_quests_account_id'), table_name='character_quests')
    op.drop_table('character_quests')
    op.drop_index(op.f('ix_character_projects_account_id'), table_name='character_projects')
    op.drop_table('character_projects')
    op.drop_table('tracker_accounts')
    # ### end Alembic commands ###
