"""add_profile_fields

Revision ID: 43f52bec417b
Revises: 2603533e5a19
Create Date: 2026-05-18 23:09:26.541294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43f52bec417b'
down_revision: Union[str, None] = '2603533e5a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_accounts', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('tracker_accounts', sa.Column('embark_id', sa.String(length=255), nullable=True))
    op.add_column('tracker_accounts', sa.Column('profile_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker_accounts', 'profile_data')
    op.drop_column('tracker_accounts', 'embark_id')
    op.drop_column('tracker_accounts', 'display_name')
    # ### end Alembic commands ###
