"""embark_status_fields

Revision ID: 526af2166f8c
Revises: 43f52bec417b
Create Date: 2026-05-18 23:46:53.006612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526af2166f8c'
down_revision: Union[str, None] = '43f52bec417b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_accounts', sa.Column('display_name_discriminator', sa.String(length=20), nullable=True))
    op.add_column('tracker_accounts', sa.Column('embark_user_id', sa.String(length=50), nullable=True))
    op.add_column('tracker_accounts', sa.Column('embark_account_id', sa.String(length=50), nullable=True))
    op.add_column('tracker_accounts', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('tracker_accounts', sa.Column('is_linked', sa.Boolean(), nullable=True))
    op.add_column('tracker_accounts', sa.Column('is_token_expired', sa.Boolean(), nullable=True))
    op.add_column('tracker_accounts', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tracker_accounts', sa.Column('embark_linked_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('tracker_accounts', 'character_name')
    op.drop_column('tracker_accounts', 'embark_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_accounts', sa.Column('embark_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tracker_accounts', sa.Column('character_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('tracker_accounts', 'embark_linked_at')
    op.drop_column('tracker_accounts', 'token_expires_at')
    op.drop_column('tracker_accounts', 'is_token_expired')
    op.drop_column('tracker_accounts', 'is_linked')
    op.drop_column('tracker_accounts', 'provider')
    op.drop_column('tracker_accounts', 'embark_account_id')
    op.drop_column('tracker_accounts', 'embark_user_id')
    op.drop_column('tracker_accounts', 'display_name_discriminator')
    # ### end Alembic commands ###
