"""add_economy_fields

Revision ID: f96bb8720de5
Revises: 526af2166f8c
Create Date: 2026-05-19 00:15:42.261079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f96bb8720de5'
down_revision: Union[str, None] = '526af2166f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_accounts', sa.Column('cred', sa.Integer(), nullable=True))
    op.add_column('tracker_accounts', sa.Column('raider_tokens', sa.Integer(), nullable=True))
    op.add_column('tracker_accounts', sa.Column('xp', sa.Integer(), nullable=True))
    op.add_column('tracker_accounts', sa.Column('used_slots', sa.Integer(), nullable=True))
    op.add_column('tracker_accounts', sa.Column('max_slots', sa.Integer(), nullable=True))
    op.add_column('tracker_accounts', sa.Column('total_value', sa.Integer(), nullable=True))
    op.add_column('tracker_accounts', sa.Column('loadout', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker_accounts', 'loadout')
    op.drop_column('tracker_accounts', 'total_value')
    op.drop_column('tracker_accounts', 'max_slots')
    op.drop_column('tracker_accounts', 'used_slots')
    op.drop_column('tracker_accounts', 'xp')
    op.drop_column('tracker_accounts', 'raider_tokens')
    op.drop_column('tracker_accounts', 'cred')
    # ### end Alembic commands ###
